### ISSUE TITLE
是不是没有离线断点下载

### ISSUE THREAD

**Issue by Buliceli** [HeroWqb/HWDownloadDemo#1]

**Comment by HeroWqb** [comment]
进程切换到后台，可以在后台继续下载；如果进程被杀死，那么将暂停下载，下次启动时，继续下载。

**Comment by Buliceli** [comment]
您说的这些 我看在iOS11上是OK的
我的iphone7系统版本是10.0.1 当我杀死程序 再次启动时 之前的下载记录有 但是需要手动继续下载 而且是从0开始下载的 并没有接着之前的下

**Comment by HeroWqb** [comment]
你是对的，在iOS 10.0、10.1系统，暂停继续下载确实存在数据错误问题。现在已经修复，同时感谢你提供的宝贵信息。
