### ISSUE TITLE
系统10.0到10.2发生了什么，我很好奇

### ISSUE THREAD

**Issue by zhouXiaoR** [HeroWqb/HWDownloadDemo#2]
大于等于10.2可以直接通过resumeData根据downloadTaskWithResumeData方法快速的寻找到task，然后执行继续下载；那么为什么10.0到10.2，寻找task需要写这么冗长的代码（downloadTaskWithCorrectResumeData）去寻找 ，另外我疑惑，像这个分类方法里面的思路代码逻辑，是楼主一步步断点调试慢慢拼接出来的么

**Comment by HeroWqb** [comment]
参考：https://stackoverflow.com/questions/39346231/resume-nsurlsession-on-ios10

**Comment by zhouXiaoR** [comment]
thanks!

**Comment by zhouXiaoR** [comment]
thanks!
