### ISSUE TITLE
localPath 取值问题

### ISSUE THREAD

**Issue by chengzj456** [HeroWqb/HWDownloadDemo#3]
- (NSString *)localPath
{
    if (!_localPath) {
        NSString *fileName = [_url substringFromIndex:[_url rangeOfString:@"/" options:NSBackwardsSearch].location + 1];
        NSString *str = [NSString stringWithFormat:@"%@_%@", _vid, fileName];
        _localPath = [[NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES) lastObject] stringByAppendingPathComponent:str];
    }
    
    return _localPath;
}
这段代码，当取不到就到本地搜索文件，而且文件是存储在caches目录中,可能会被清掉，查找不到的时候，没有再到数据库中寻找，是不是这样才会更合理些？

还有下载过程中，拿到的speed为nil ,我看代码写的是 
 if (intervals >= 1) {
        // 计算速度
        model.speed = model.intervalFileSize / intervals;

        // 重置变量
        model.intervalFileSize = 0;
        model.lastSpeedTime = [HWToolBox getTimeStampWithDate:[NSDate date]];
    }
我断点看intervalFileSize <  intervals ，而且speed 为整型，这样就怎么都拿不到速度了～

**Comment by HeroWqb** [comment]
localPath // 下载完成路径，是相对路径，不能写成绝对路径保存到数据库，这个get方法只是用文件名字+标识拼接获取路径而已。

计算速度，if (intervals >= 1)是每秒计算一次，intervals值为1，intervalFileSize是获取的字节数，每次回调你获取的字节数<1，那应该是你网络有问题，肯定计算不到速度的。
NSLog(@"intervalFileSize: %ld, intervals: %ld", model.intervalFileSize, intervals);
2018-07-30 11:11:09.349 HWDownloadDemo[1054:35003] intervalFileSize: 3546616, intervals: 1
2018-07-30 11:11:10.350 HWDownloadDemo[1054:34999] intervalFileSize: 2040168, intervals: 1
2018-07-30 11:11:11.353 HWDownloadDemo[1054:35001] intervalFileSize: 5484888, intervals: 1
2018-07-30 11:11:12.357 HWDownloadDemo[1054:34999] intervalFileSize: 7325528, intervals: 1
这是输出信息，你可以看到正常网络情况下这个字节数值是非常大的。
