### ISSUE TITLE
iOS10系统下切换到后台，再切换到页面，下载 暂停那块有问题 ，楼主有发现吗 

### ISSUE THREAD

**Issue by Baiyongyu** [HeroWqb/HWDownloadDemo#4]

**Comment by HeroWqb** [comment]
没有iOS 10系统的真机，用模拟器测试过是没有问题的，你可以具体说明一下操作流程及出现的问题么。

**Comment by Baiyongyu** [comment]
1、下载的时候，切换到后台，然后再切换到前台，有时iOS10 暂停就不好使了
2、暂停的时候不会立刻停止，还会下载一点点
3、iOS11.0.4 反复下载暂停还是有问题，易导致重新下载

**Comment by Baiyongyu** [comment]
11.0.2 ，应该是 < 11.2系统的问题

**Comment by HeroWqb** [comment]
谢谢，demo确实还不够完善。
第一点没有测试出来，想了一下原因，有可能和第二点相同，暂停调用cancelTaskWithModel方法时，代理方法可能会继续调用一断时间，如果这段时间刚好下载完成，那体验应该就是没有暂停了。
第二点原因上面说了，想要立刻停止可以在代理方法中加判断，这里不具体写了。
第三点重新下载的问题，我只测出一种可能，正在下载时，当点击暂停的瞬间，同时下载完成，这时会先响应-URLSession: task: didCompleteWithError这个回调，将任务模型中状态更新为完成，然后调用暂停方法中，更新状态为暂停，这时，这个任务显示状态为暂停，但实际已经下载完成，再次点击下载按钮会造成任务重新下载。解决方法是在HWDataBaseManager.m文件235行代码，更改一下发送状态变更通知的判断条件，改为(oldState != model.state && oldState != HWDownloadStateFinish)，即当原状态与新状态不同，并且原状态不是已完成时在发送通知。

**Comment by Baiyongyu** [comment]
多谢楼主指点，我再看看。希望后期有时间楼主能够优化下，封装的很好，项目中有用到

**Comment by HeroWqb** [comment]
不客气，有时间会进行优化，共同进步~
