### ISSUE TITLE
后台下载有问题和 cpu 使用过高

### ISSUE THREAD

**Issue by mahuiying0126** [HeroWqb/HWDownloadDemo#5]
在 appdelegate 里面向系统借时间来达到后台下载的目的,借的时间是有限的,每一次调用此方法都应该有对应的endBackgroundTask:方法，app的后台运行时间是有限的（你可以通过backgroundTimeRemaining属性来获取这个可用时间）如果在这个时间耗尽之前你没有调用endBackgroundTask:方法来结束相应的每个后台任务，系统就会杀掉这个app。

一个下载任务时 cpu使用率就达到了21%(iPhone6 真机),而且频点按钮时,状态错乱,下载进度仍然在继续

**Comment by HeroWqb** [comment]
程序终止，再次启动继续下载：

在应用程序被杀掉时，系统会自动保存应用下载session信息，重新启动应用时，如果创建和之前相同identifier的session，系统会找到对应的session数据，并响应-URLSession: task: didCompleteWithError:方法，可以拿到resumeData，用resumeData创建task，就可以恢复下载。

再说明一下，另外一种不可取的思路，在appDelegate中进程杀死时会调用-applicationWillTerminate:方法，在这里task调用cancelByProducingResumeData:方法暂停正在下载的任务，但是这个方法的回调需要时间，还没有执行到代码块进程就已经终止了。
